### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by KareemMAX** [KareemMAX/Minecraft-Skiner#10]
- [ ] Layers
- [ ] Effects
- [ ] 2D Edit
- [ ] Add grid
- [ ] Improved GUI (More like photoshop)
- [ ] New menu to make fast custom skins
- [ ] Use the app to render the skin with custom styles

**Comment by KareemMAX** [comment]
The repo is now deprecated, closing this issue
